services:
  # Backend API (frontend ham serve qiladi)
  - type: web
    name: map-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: ALLOWED_ORIGINS
        value: https://map-backend.onrender.com,https://your-bot-domain.com
      - key: NODE_ENV
        value: production

  # Frontend Static Site
  - type: web
    name: map-frontend
    env: static
    staticPublishPath: ./frontend
